---
name: "Release"

on: workflow_dispatch

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  build_rcc:
    uses: ./.github/workflows/rcc.yaml
  build_robotmk:
    uses: ./.github/workflows/robotmk_build.yaml
  release:
    runs-on: ubuntu-latest
    needs: [build_rcc, build_robotmk, tests]
    steps:
      - uses: actions/download-artifact@v3

      - run: zip -r executables.zip artifact

      - name: Push release tag
        run: |
          git checkout main
          git tag v2.0.0-alpha
          git push --tags
