---
name: "Upload all artifacts"
on:
  push:
    tags:
    - '*'

jobs:
  build_rcc:
    uses: ./.github/workflows/rcc.yaml
  build_robotmk:
    uses: ./.github/workflows/robotmk.yaml
  release:
    runs-on: ubuntu-latest
    needs: [build_rcc, build_robotmk]
    steps:
      - uses: actions/download-artifact@v3

      - run: zip -r executables.zip artifact

      - uses: ncipollo/release-action@v1.13.0
        with:
          name: "Daily Build"
          allowUpdates: false
          artifacts: "executables.zip"
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: true
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          makeLatest: false
          tag: "v2release"
