---
name: "Build Robotmk"

on:
  workflow_call: {}

jobs:
  build_robotmk_from_source:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu

      - run: cargo build --target=x86_64-pc-windows-gnu --release

      - uses: actions/upload-artifact@v4
        with:
          name: rmk_windows64
          path: ${{ github.workspace }}/target/x86_64-pc-windows-gnu/release/
          if-no-files-found: error

