---
name: "Build Robotmk"

on:
  workflow_call:
    outputs:
      artifact_id:
        value: ${{ jobs.build_robotmk.outputs.artifact_id }}
jobs:
  build_robotmk:
    runs-on: windows-latest
    outputs:
      artifact_id: ${{ steps.artifact_upload_step.outputs.artifact_id }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu

      - run: cargo build --target=x86_64-pc-windows-gnu --release

      - uses: actions/upload-artifact@v4
        id: artifact_upload_step
        with:
          name: rmk_windows64
          path: |
            ${{ github.workspace }}/target/x86_64-pc-windows-gnu/release/robotmk_scheduler.exe
            ${{ github.workspace }}/target/x86_64-pc-windows-gnu/release/robotmk_agent_plugin.exe
          if-no-files-found: error
