---
name: "System tests"

on:
  workflow_call:
    inputs:
      rcc_artifact_id:
        required: true
        type: string
jobs:
  test_scheduler:
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: C:\
          rcc_artifact_id: ${{ inputs.rcc_artifact_id }}
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          target: x86_64-pc-windows-gnu
      - run: cargo test --target=x86_64-pc-windows-gnu --test test_scheduler -- --nocapture --ignored
        env:
          TEST_DIR: C:\test_scheduler
          RCC_BINARY_PATH: C:\artifact\windows64\rcc.exe
          RUN_FOR: 240
      - uses: actions/upload-artifact@v4
        with:
          name: system_test_debug_information
          path: C:\test_scheduler
